name: learn-github-actions
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    # - name: Check out
    #   uses: actions/checkout@v2

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Nuget packages
      run: nuget restore test-application\test-application.sln

    - name: Build
      run: msbuild test-application\test-application.sln /p:Configuration=Release

    - name: Get file version
      id: vars
      shell: pwsh
      run: $file_path = "${{ github.workspace }}\test-application\test-application\bin\release\test-application.exe";
           $file_version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($file_path).FileVersion;
           echo "::set-output name=version::$file_version"
           echo ${{ steps.vars.outputs.version }}

    - uses: actions/checkout@v2
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}


