name: learn-github-actions
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Nuget packages
      run: nuget restore test-application\test-application.sln

    - name: Build
      run: msbuild test-application\test-application.sln /p:Configuration=Release

    - name: Get file version
      id: vars
      shell: pwsh
      run: $file_path = "${{ github.workspace }}\test-application\bin\release\test-application.exe";
           $file_version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($file_path).FileVersion;
           echo "::set-output name=version::$file_version"
           echo ${{ steps.vars.outputs.version }}
